services:
  louchebem-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: louchebem
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t /app/public